{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "book.serviceAccountName" . }}
  labels:
{{ include "book.labels" . | indent 4 }}
{{- end -}}
