{{- if .Values.unrealircd.includes }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ $root := . }}
{{- range .Values.unrealircd.includes }}
  {{ template "adjusted-file-name" .src }}: |-
{{- if and (.type) (eq .type "template") }}
{{ tpl ($root.Files.Get (include "fromConfigs" .src)) $root | indent 4 }}
{{- else }}
{{ $root.Files.Get (include "fromConfigs" .src) | indent 4 }}
{{- end }}
{{- end }}
{{ end }}
