apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: irc
    port: 6667
    protocol: TCP
    targetPort: ircd
  - name: irc-websocket
    port: 6800
    protocol: TCP
    targetPort: irc-websocket
  - name: services
    port: 7000
    protocol: TCP
    targetPort: services
